import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Montserrat } from 'next/font/google';
import Cursor from "@/components/Cursor";

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: [ '300', '400', '500', '700']
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} font-sans`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
